name: Build aapt2

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    strategy:
      matrix:
        target_arch: [x86_64, x86, arm64-v8a, armeabi-v7a]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setting up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Getting AOSP's source code
        run: |
          python3 ./get_source.py --tags platform-tools-35.0.2

      - name: Compiling protoc
        run: |
          mkdir -p src/protobuf/build
          pushd src/protobuf/build
          cmake -GNinja -Dprotobuf_BUILD_TESTS=OFF ..
          ninja -j$(nproc --all)
          popd
        env:
          NDK_TOOLCHAIN: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64

      - name: Compiling aapt2
        run: python3 ./build.py --ndk=${{ steps.setup-ndk.outputs.ndk-path }} --abi=${{ matrix.target_arch }} --build="build/${{ matrix.target_arch }}" --protoc=/${{ github.workspace }}/src/protobuf/build/protoc --target aapt2
        env:
          NDK_TOOLCHAIN: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aapt2-${{ matrix.target_arch }}
          path: ${{ github.workspace }}/build/${{ matrix.target_arch }}/bin/aapt2
